#!/bin/bash

# Lab 132: Networking Fundamentals — Fix Slow Hostname Lookups (Reverse DNS) (4–8 prompts)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$ROOT_DIR/scripts/ui.sh" || { echo "Failed to source ui.sh"; exit 1; }
source "$ROOT_DIR/scripts/xp.sh" || { echo "Failed to source xp.sh"; exit 1; }

LAB_NAME="Lab 132: Networking Fundamentals — Fix Slow Host Lookups"
LAB_ID="lab132"
LAB_XP=22500
LAB_TRACK_FILE="$ROOT_DIR/data/.lab_completions.json"
[ ! -f "$LAB_TRACK_FILE" ] && echo '{}' > "$LAB_TRACK_FILE"

PROMPT="  lab@rhel-lab132:~$ "

draw_lab_ui() {
  clear
  center_draw_stats_panel "$LEVEL" "$XP" "$(calculate_xp_to_next_level)"
  center_draw_progress_bar "$XP" "$(calculate_xp_to_next_level)"
  echo; echo; echo
}

record_lab_completion() {
  tmpfile=$(mktemp)
  jq --arg lab "$LAB_ID" '.[$lab] += 1 // 1' "$LAB_TRACK_FILE" > "$tmpfile" && mv "$tmpfile" "$LAB_TRACK_FILE"
}

get_lab_completion_count() {
  jq -r --arg lab "$LAB_ID" '.[$lab] // 0' "$LAB_TRACK_FILE"
}

while true; do
  draw_lab_ui
  center_title "$LAB_NAME"
  echo
  center_text "Scenario:"
  center_text "Users complain: 'SSH and sudo feel slow on this server.'"
  center_text "You suspect hostname resolution delays (reverse DNS / resolver timeouts)."
  echo
  center_text "Goal: confirm the lookup delay, adjust host resolution order, and verify it's fixed."
  echo
  center_text "Press Enter to begin the lab..."
  read _
  draw_lab_ui

  # STEP 1: Measure a lookup that should be instant (but is slow)
  echo "  Step 1: Measure how long a hostname lookup takes (use time + getent)."
  read -p "$PROMPT" cmd1
  echo
  if [[ "$cmd1" != "time getent hosts portal.lab.local" && \
        "$cmd1" != "/usr/bin/time getent hosts portal.lab.local" && \
        "$cmd1" != "time getent hosts localhost" && \
        "$cmd1" != "/usr/bin/time getent hosts localhost" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  10.0.2.50   portal.lab.local"
  echo
  echo "  real    0m2.01s"
  echo "  user    0m0.00s"
  echo "  sys     0m0.00s"
  echo

  # STEP 2: Check current resolver settings
  echo "  Step 2: Check which DNS server(s) this host is using."
  read -p "$PROMPT" cmd2
  echo
  if [[ "$cmd2" != "resolvectl status" && \
        "$cmd2" != "sudo resolvectl status" && \
        "$cmd2" != "cat /etc/resolv.conf" && \
        "$cmd2" != "sudo cat /etc/resolv.conf" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  if [[ "$cmd2" == *"resolvectl status"* ]]; then
    echo "  Link 2 (eth0)"
    echo "       DNS Servers: 10.0.2.99"
    echo "  Current DNS Server: 10.0.2.99"
  else
    echo "  # Generated by NetworkManager"
    echo "  nameserver 10.0.2.99"
  fi
  echo

  # STEP 3: Prove DNS is timing out (query the current server explicitly)
  echo "  Step 3: Test whether the configured DNS server responds (query portal.lab.local)."
  read -p "$PROMPT" cmd3
  echo
  if [[ "$cmd3" != "dig @10.0.2.99 portal.lab.local" && \
        "$cmd3" != "sudo dig @10.0.2.99 portal.lab.local" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  ;; communications error to 10.0.2.99#53: timed out"
  echo "  ;; communications error to 10.0.2.99#53: timed out"
  echo "  ;; no servers could be reached"
  echo

  # STEP 4: Inspect the host lookup order
  echo "  Step 4: Check the 'hosts:' line in /etc/nsswitch.conf."
  read -p "$PROMPT" cmd4
  echo
  if [[ "$cmd4" != "grep -n '^hosts:' /etc/nsswitch.conf" && \
        "$cmd4" != "sudo grep -n '^hosts:' /etc/nsswitch.conf" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  12:hosts: dns files myhostname"
  echo

  # STEP 5: Edit nsswitch.conf to prefer files before dns
  echo "  Step 5: Edit /etc/nsswitch.conf and change hosts lookup order to: files dns myhostname"
  read -p "$PROMPT" cmd5
  echo
  if [[ "$cmd5" != "sudo vim /etc/nsswitch.conf" && \
        "$cmd5" != "sudo vi /etc/nsswitch.conf" && \
        "$cmd5" != "sudo nano /etc/nsswitch.conf" && \
        "$cmd5" != "sudoedit /etc/nsswitch.conf" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  (editor opened)"
  echo "  (updated hosts: line and saved)"
  echo

  # STEP 6: Re-test lookup speed (should be fast now)
  echo "  Step 6: Re-measure the lookup time after the change."
  read -p "$PROMPT" cmd6
  echo
  if [[ "$cmd6" != "time getent hosts portal.lab.local" && \
        "$cmd6" != "/usr/bin/time getent hosts portal.lab.local" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  10.0.2.50   portal.lab.local"
  echo
  echo "  real    0m0.01s"
  echo "  user    0m0.00s"
  echo "  sys     0m0.00s"
  echo

  # STEP 7: Verify the host is responsive for an admin workflow (quick sanity check)
  echo "  Step 7: Quick sanity check: resolve portal.lab.local and fetch HTTP headers."
  read -p "$PROMPT" cmd7
  echo
  if [[ "$cmd7" != "curl -I http://portal.lab.local" && \
        "$cmd7" != "curl -I http://portal.lab.local/" && \
        "$cmd7" != "getent hosts portal.lab.local" && \
        "$cmd7" != "dig +short portal.lab.local" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  if [[ "$cmd7" == "curl -I"* ]]; then
    echo "  HTTP/1.1 200 OK"
    echo "  Content-Type: text/html; charset=UTF-8"
    echo "  Server: nginx"
  elif [[ "$cmd7" == "dig +short portal.lab.local" ]]; then
    echo "  10.0.2.50"
  else
    echo "  10.0.2.50   portal.lab.local"
  fi
  echo

  print_success "Nice work."
  print_info "You fixed a real 'network feels slow' issue by:"
  print_info "- measuring lookup latency with time + getent"
  print_info "- identifying an unresponsive DNS server"
  print_info "- confirming host lookup order was DNS-first"
  print_info "- changing /etc/nsswitch.conf to prefer files before dns"
  print_info "- verifying resolution time improved dramatically"
  print_info "You earned $LAB_XP XP for completing this lab."
  award_xp $LAB_XP

  XP=$(jq '.XP' "$SAVE_JSON"); LEVEL=$(jq '.LEVEL' "$SAVE_JSON"); export XP; export LEVEL
  record_lab_completion

  completion_count=$(get_lab_completion_count)
  echo
  print_info "You've successfully completed this lab $completion_count time(s)."
  echo
  center_text "Would you like to:"
  center_text "1) Retry this lab"
  center_text "2) Return to Sysadmin Lab Menu"
  echo
  read -p "  > " post_choice
  [[ "$post_choice" == "2" ]] && exit 0
done
