#!/bin/bash

# Lab 131: Networking Fundamentals — Fix Hostname Override + Verify DNS Path (4–8 prompts)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$ROOT_DIR/scripts/ui.sh" || { echo "Failed to source ui.sh"; exit 1; }
source "$ROOT_DIR/scripts/xp.sh" || { echo "Failed to source xp.sh"; exit 1; }

LAB_NAME="Lab 131: Networking Fundamentals — Fix Hostname Override"
LAB_ID="lab131"
LAB_XP=29500
LAB_TRACK_FILE="$ROOT_DIR/data/.lab_completions.json"
[ ! -f "$LAB_TRACK_FILE" ] && echo '{}' > "$LAB_TRACK_FILE"

PROMPT="  lab@rhel-lab131:~$ "

draw_lab_ui() {
  clear
  center_draw_stats_panel "$LEVEL" "$XP" "$(calculate_xp_to_next_level)"
  center_draw_progress_bar "$XP" "$(calculate_xp_to_next_level)"
  echo; echo; echo
}

record_lab_completion() {
  tmpfile=$(mktemp)
  jq --arg lab "$LAB_ID" '.[$lab] += 1 // 1' "$LAB_TRACK_FILE" > "$tmpfile" && mv "$tmpfile" "$LAB_TRACK_FILE"
}

get_lab_completion_count() {
  jq -r --arg lab "$LAB_ID" '.[$lab] // 0' "$LAB_TRACK_FILE"
}

while true; do
  draw_lab_ui
  center_title "$LAB_NAME"
  echo
  center_text "Scenario:"
  center_text "Users report the internal app at portal.lab.local is loading the WRONG environment."
  center_text "Ticket notes: 'It looks like this host resolves portal.lab.local to 127.0.0.1.'"
  center_text "You must confirm the resolution path, remove any bad /etc/hosts override,"
  center_text "verify DNS is used, and confirm the service is reachable."
  echo
  center_text "Expected DNS result (from the ticket): portal.lab.local -> 10.0.2.50"
  center_text "Verification target: http://portal.lab.local"
  echo
  center_text "Press Enter to begin the lab..."
  read _
  draw_lab_ui

  # STEP 1: Confirm current resolution
  echo "  Step 1: Check what IP portal.lab.local resolves to on this host."
  read -p "$PROMPT" cmd1
  echo
  if [[ "$cmd1" != "getent hosts portal.lab.local" && \
        "$cmd1" != "getent ahosts portal.lab.local" && \
        "$cmd1" != "dig +short portal.lab.local" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  if [[ "$cmd1" == dig* ]]; then
    echo "  10.0.2.50"
  else
    echo "  127.0.0.1   portal.lab.local"
  fi
  echo

  # STEP 2: Search /etc/hosts for an override
  echo "  Step 2: Check /etc/hosts for an entry that mentions portal.lab.local."
  read -p "$PROMPT" cmd2
  echo
  if [[ "$cmd2" != "grep -n portal.lab.local /etc/hosts" && \
        "$cmd2" != "sudo grep -n portal.lab.local /etc/hosts" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  6:127.0.0.1 portal.lab.local portal"
  echo

  # STEP 3: Edit /etc/hosts to remove the bad mapping
  echo "  Step 3: Edit /etc/hosts and remove the portal.lab.local override line."
  read -p "$PROMPT" cmd3
  echo
  if [[ "$cmd3" != "sudo vim /etc/hosts" && \
        "$cmd3" != "sudo vi /etc/hosts" && \
        "$cmd3" != "sudo nano /etc/hosts" && \
        "$cmd3" != "sudoedit /etc/hosts" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  (editor opened)"
  echo "  (removed the bad line and saved)"
  echo

  # STEP 4: Confirm resolution now comes from DNS (should be 10.0.2.50)
  echo "  Step 4: Re-check resolution and confirm portal.lab.local resolves to 10.0.2.50."
  read -p "$PROMPT" cmd4
  echo
  if [[ "$cmd4" != "getent hosts portal.lab.local" && \
        "$cmd4" != "dig +short portal.lab.local" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  if [[ "$cmd4" == "dig +short portal.lab.local" ]]; then
    echo "  10.0.2.50"
  else
    echo "  10.0.2.50   portal.lab.local"
  fi
  echo

  # STEP 5: Verify the resolver configuration (sanity check)
  echo "  Step 5: Check which DNS server(s) this host is using."
  read -p "$PROMPT" cmd5
  echo
  if [[ "$cmd5" != "resolvectl status" && \
        "$cmd5" != "sudo resolvectl status" && \
        "$cmd5" != "cat /etc/resolv.conf" && \
        "$cmd5" != "sudo cat /etc/resolv.conf" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  if [[ "$cmd5" == *"resolvectl status"* ]]; then
    echo "  Link 2 (eth0)"
    echo "       DNS Servers: 10.0.2.3"
    echo "  Current DNS Server: 10.0.2.3"
  else
    echo "  # Generated by NetworkManager"
    echo "  nameserver 10.0.2.3"
  fi
  echo

  # STEP 6: Verify the app endpoint is reachable
  echo "  Step 6: Verify the portal responds over HTTP."
  read -p "$PROMPT" cmd6
  echo
  if [[ "$cmd6" != "curl -I http://portal.lab.local" && \
        "$cmd6" != "curl -I http://portal.lab.local/" && \
        "$cmd6" != "curl -sS http://portal.lab.local | head" && \
        "$cmd6" != "curl -sS http://portal.lab.local/ | head" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  if [[ "$cmd6" == "curl -I"* ]]; then
    echo "  HTTP/1.1 200 OK"
    echo "  Content-Type: text/html; charset=UTF-8"
    echo "  Server: nginx"
  else
    echo "  <html>"
    echo "  <head><title>Portal</title></head>"
    echo "  <body>OK</body>"
    echo "  </html>"
  fi
  echo

  print_success "Nice work."
  print_info "You fixed a real hostname-resolution outage by:"
  print_info "- confirming the bad resolution"
  print_info "- locating an /etc/hosts override"
  print_info "- removing the override safely"
  print_info "- validating DNS resolution to the correct IP"
  print_info "- verifying the application endpoint responds"
  print_info "You earned $LAB_XP XP for completing this lab."
  award_xp $LAB_XP

  XP=$(jq '.XP' "$SAVE_JSON"); LEVEL=$(jq '.LEVEL' "$SAVE_JSON"); export XP; export LEVEL
  record_lab_completion

  completion_count=$(get_lab_completion_count)
  echo
  print_info "You've successfully completed this lab $completion_count time(s)."
  echo
  center_text "Would you like to:"
  center_text "1) Retry this lab"
  center_text "2) Return to Sysadmin Lab Menu"
  echo
  read -p "  > " post_choice
  [[ "$post_choice" == "2" ]] && exit 0
done
