#!/bin/bash

# Lab 465: RHEL Storage — Filesystem Labels + fstab Edits (Mount + Swap Entry Mistake Simulation)
# Focus: creating filesystems with labels, mounting/unmounting, editing /etc/fstab safely, and
# managing labels with xfs_admin. This lab intentionally includes a common "fstab swap line mistake"
# scenario so you practice spotting it before reboot.
# Key skills: cat /etc/fstab, mkfs.xfs -L, mkfs.ext4 -N, mount/umount, mkdir,
# /etc/fstab editing, xfs_admin -L, blkid (optional), mount -a (safe validation).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$ROOT_DIR/scripts/ui.sh" || { echo "Failed to source ui.sh"; exit 1; }
source "$ROOT_DIR/scripts/xp.sh" || { echo "Failed to source xp.sh"; exit 1; }

LAB_NAME="Lab 465: Filesystem Labels + fstab (Mount + Swap Entry)"
LAB_ID="lab465"
LAB_XP=46500
LAB_TRACK_FILE="$ROOT_DIR/data/.lab_completions.json"

[ ! -f "$LAB_TRACK_FILE" ] && echo '{}' > "$LAB_TRACK_FILE"

draw_lab_ui() {
  clear
  center_draw_stats_panel "$LEVEL" "$XP" "$(calculate_xp_to_next_level)"
  center_draw_progress_bar "$XP" "$(calculate_xp_to_next_level)"
  echo
  echo
}

record_lab_completion() {
  tmpfile=$(mktemp)
  jq --arg lab "$LAB_ID" '.[$lab] += 1 // 1' "$LAB_TRACK_FILE" > "$tmpfile" && mv "$tmpfile" "$LAB_TRACK_FILE"
}

get_lab_completion_count() {
  jq -r --arg lab "$LAB_ID" '.[$lab] // 0' "$LAB_TRACK_FILE"
}

while true; do
  draw_lab_ui
  center_title "$LAB_NAME"
  echo
  center_text "Scenario:"
  center_text "A host needs two fresh filesystems prepared and an /etc/fstab update."
  center_text "You will:"
  center_text "- Create an XFS filesystem on /dev/vdb with label DataDisk"
  center_text "- Create an ext4 filesystem on /dev/vdc with 2048 inodes"
  center_text "- Practice mount/umount"
  center_text "- Create /test and add an fstab entry for /dev/vdc -> /test"
  center_text "- Simulate a common mistake: a bad swap entry for /dev/vdb in fstab"
  center_text "- Fix it safely (no reboot) and update XFS label to SwapFS using xfs_admin"
  echo
  center_text "Goal: perform tasks AND validate changes safely with mount -a."
  echo
  center_text "Press Enter to begin the lab..."
  read _
  draw_lab_ui

  # STEP 1: View current fstab
  echo "  Step 1: View /etc/fstab."
  read -p "  lab@rhel-lab463:~$ " cmd1
  echo
  if [[ "$cmd1" != "cat /etc/fstab" && \
        "$cmd1" != "sudo cat /etc/fstab" && \
        "$cmd1" != "less /etc/fstab" && \
        "$cmd1" != "sudo less /etc/fstab" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  #"
  echo "  # /etc/fstab"
  echo "  # Created by anaconda on Mon Oct  7 04:10:48 2024"
  echo "  #"
  echo "  # Accessible filesystems, by reference, are maintained under '/dev/disk/'."
  echo "  # See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info."
  echo "  #"
  echo "  # After editing this file, run 'systemctl daemon-reload' to update systemd"
  echo "  # units generated from this file."
  echo "  #"
  echo "  UUID=ef8dfc97-1a96-4105-ade9-a8f014c59f27 /                       ext4    defaults        1 1"
  echo "  /swapfile none swap defaults 0 0"
  echo "  #VAGRANT-BEGIN"
  echo "  # The contents below are automatically generated by Vagrant. Do not modify."
  echo "  #VAGRANT-END"
  echo

  # STEP 2: Create XFS filesystem with label
  echo "  Step 2: Create an XFS filesystem on /dev/vdb with label DataDisk."
  read -p "  lab@rhel-lab463:~$ " cmd2
  echo
  if [[ "$cmd2" != "sudo mkfs.xfs -L \"DataDisk\" /dev/vdb" && \
        "$cmd2" != "sudo mkfs.xfs -L DataDisk /dev/vdb" && \
        "$cmd2" != "mkfs.xfs -L \"DataDisk\" /dev/vdb" && \
        "$cmd2" != "mkfs.xfs -L DataDisk /dev/vdb" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  meta-data=/dev/vdb               isize=512    agcount=4, agsize=65536 blks"
  echo "           =                       sectsz=512   attr=2, projid32bit=1"
  echo "           =                       crc=1        finobt=1, sparse=1, rmapbt=0"
  echo "           =                       reflink=1    bigtime=1 inobtcount=1 nrext64=0"
  echo "  data     =                       bsize=4096   blocks=262144, imaxpct=25"
  echo "           =                       sunit=0      swidth=0 blks"
  echo "  naming   =version 2              bsize=4096   ascii-ci=0, ftype=1"
  echo "  log      =internal log           bsize=4096   blocks=16384, version=2"
  echo "           =                       sectsz=512   sunit=0 blks, lazy-count=1"
  echo "  realtime =none                   extsz=4096   blocks=0, rtextents=0"
  echo

  # STEP 3: Create ext4 filesystem with 2048 inodes
  echo "  Step 3: Create an ext4 filesystem on /dev/vdc with 2048 inodes."
  read -p "  lab@rhel-lab463:~$ " cmd3
  echo
  if [[ "$cmd3" != "sudo mkfs.ext4 -N 2048 /dev/vdc" && \
        "$cmd3" != "mkfs.ext4 -N 2048 /dev/vdc" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  mke2fs 1.46.5 (30-Dec-2021)"
  echo "  Creating filesystem with 262144 4k blocks and 2048 inodes"
  echo "  Filesystem UUID: 382ebd9a-9cc8-412d-b700-fb5dbf38e7e4"
  echo "  Superblock backups stored on blocks:"
  echo "          32768, 98304, 163840, 229376"
  echo
  echo "  Allocating group tables: done"
  echo "  Writing inode tables: done"
  echo "  Creating journal (8192 blocks): done"
  echo "  Writing superblocks and filesystem accounting information: done"
  echo

  # STEP 4: Mount /dev/vdb on /mnt
  echo "  Step 4: Mount /dev/vdb at /mnt."
  read -p "  lab@rhel-lab463:~$ " cmd4
  echo
  if [[ "$cmd4" != "sudo mount /dev/vdb /mnt" && \
        "$cmd4" != "mount /dev/vdb /mnt" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi

  # STEP 5: Unmount /mnt
  echo "  Step 5: Unmount /mnt."
  read -p "  lab@rhel-lab463:~$ " cmd5
  echo
  if [[ "$cmd5" != "sudo umount /mnt" && \
        "$cmd5" != "umount /mnt" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi

  # STEP 6: Create /test directory
  echo "  Step 6: Create mount directory /test."
  read -p "  lab@rhel-lab463:~$ " cmd6
  echo
  if [[ "$cmd6" != "sudo mkdir /test" && \
        "$cmd6" != "sudo mkdir -p /test" && \
        "$cmd6" != "mkdir /test" && \
        "$cmd6" != "mkdir -p /test" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi

  # STEP 7: Edit /etc/fstab to add entries (includes intentional bad swap line)
  echo "  Step 7: Edit /etc/fstab."
  echo "          Add an entry to mount /dev/vdc at /test as ext4."
  echo "          Also add a swap entry for /dev/vdb (this is intentionally incorrect to practice recovery)."
  read -p "  lab@rhel-lab463:~$ " cmd7
  echo
  if [[ "$cmd7" != "sudo vi /etc/fstab" && \
        "$cmd7" != "sudo vim /etc/fstab" && \
        "$cmd7" != "sudo nano /etc/fstab" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  (editor opened)"
  echo "  (added lines and saved)"
  echo
  echo "  /dev/vdc  /test  ext4  defaults  0  2"
  echo "  /dev/vdb  none   swap  defaults  0  0"
  echo

  # STEP 8: Validate fstab safely (should fail due to wrong swap entry)
  echo "  Step 8: Validate /etc/fstab safely (expect an error)."
  read -p "  lab@rhel-lab463:~$ " cmd8
  echo
  if [[ "$cmd8" != "sudo mount -a" && \
        "$cmd8" != "mount -a" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  mount: /test: /dev/vdc mounted on /test."
  echo "  mount: /dev/vdb: can't find in /etc/fstab."
  echo "  swapon: /dev/vdb: read swap header failed"
  echo

  # STEP 9: Fix the bad swap entry (comment it out)
  echo "  Step 9: Fix the bad swap entry in /etc/fstab (comment it out)."
  read -p "  lab@rhel-lab463:~$ " cmd9
  echo
  if [[ "$cmd9" != "sudo vi /etc/fstab" && \
        "$cmd9" != "sudo vim /etc/fstab" && \
        "$cmd9" != "sudo nano /etc/fstab" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  (commented out the swap line and saved)"
  echo "  #/dev/vdb  none  swap  defaults  0  0"
  echo

  # STEP 10: Re-validate fstab (should succeed)
  echo "  Step 10: Re-validate /etc/fstab (should succeed with no errors)."
  read -p "  lab@rhel-lab463:~$ " cmd10
  echo
  if [[ "$cmd10" != "sudo mount -a" && \
        "$cmd10" != "mount -a" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi

  # STEP 11: Relabel XFS filesystem using xfs_admin
  echo "  Step 11: Change the XFS label on /dev/vdb to SwapFS."
  read -p "  lab@rhel-lab463:~$ " cmd11
  echo
  if [[ "$cmd11" != "sudo xfs_admin -L \"SwapFS\" /dev/vdb" && \
        "$cmd11" != "sudo xfs_admin -L SwapFS /dev/vdb" && \
        "$cmd11" != "xfs_admin -L \"SwapFS\" /dev/vdb" && \
        "$cmd11" != "xfs_admin -L SwapFS /dev/vdb" ]]; then
    print_error "Incorrect."
    read -p "Press Enter to try again..." _
    continue
  fi
  echo "  writing all SBs"
  echo "  new label = \"SwapFS\""
  echo

  print_success "Great job."
  print_info "You practiced filesystem creation, labeling, mount verification, and safe fstab recovery:"
  print_info "- created XFS with label DataDisk on /dev/vdb"
  print_info "- created ext4 on /dev/vdc with 2048 inodes"
  print_info "- mounted/umounted /dev/vdb on /mnt"
  print_info "- created /test and added a persistent mount for /dev/vdc via /etc/fstab"
  print_info "- safely detected and fixed a bad swap entry using mount -a (no reboot required)"
  print_info "- updated the XFS label to SwapFS using xfs_admin"
  print_info "You earned $LAB_XP XP for completing this lab."
  award_xp $LAB_XP

  XP=$(jq '.XP' "$SAVE_JSON")
  LEVEL=$(jq '.LEVEL' "$SAVE_JSON")
  export XP
  export LEVEL
  record_lab_completion

  completion_count=$(get_lab_completion_count)
  echo
  print_info "You've successfully completed this lab $completion_count time(s)."
  echo
  center_text "Would you like to:"
  center_text "1) Retry this lab"
  center_text "2) Return to Sysadmin Lab Menu"
  echo
  read -p "  > " choice

  [[ "$choice" == "2" ]] && exit 0
done
