#!/bin/bash

# Lab 516: Configure Hostname Resolution (Rocky Linux 10 / RHCSA)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$ROOT_DIR/scripts/ui.sh" || { echo "Failed to source ui.sh"; exit 1; }
source "$ROOT_DIR/scripts/xp.sh" || { echo "Failed to source xp.sh"; exit 1; }

LAB_NAME="Lab 516: Configure Hostname Resolution (Rocky 10 / RHCSA)"
LAB_ID="lab516"
LAB_XP=51600
LAB_TRACK_FILE="$ROOT_DIR/data/.lab_completions.json"
[ ! -f "$LAB_TRACK_FILE" ] && echo '{}' > "$LAB_TRACK_FILE"

PROMPT="  examuser@rhel-lab516:~$ "

draw_lab_ui() {
  clear
  center_draw_stats_panel "$LEVEL" "$XP" "$(calculate_xp_to_next_level)"
  center_draw_progress_bar "$XP" "$(calculate_xp_to_next_level)"
  echo; echo; echo
}

record_lab_completion() {
  tmpfile=$(mktemp)
  jq --arg lab "$LAB_ID" '.[$lab] += 1 // 1' "$LAB_TRACK_FILE" > "$tmpfile" && mv "$tmpfile" "$LAB_TRACK_FILE"
}

get_lab_completion_count() {
  jq -r --arg lab "$LAB_ID" '.[$lab] // 0' "$LAB_TRACK_FILE"
}

while true; do
  draw_lab_ui
  center_title "$LAB_NAME"
  echo
  center_text "Scenario:"
  center_text "Users report that hostnames are not resolving reliably."
  center_text "You must verify current resolver settings, configure DNS via nmcli,"
  center_text "add a local override using /etc/hosts, and validate resolution."
  echo
  center_text "Targets:"
  center_text "- Interface/connection: eth0"
  center_text "- DNS server: 8.8.8.8"
  center_text "- Local host entry: 192.168.50.100 webserver"
  echo
  center_text "Press Enter to begin..."
  read _
  draw_lab_ui

  echo "  Step 1: Verify current DNS configuration applied to eth0."
  read -p "$PROMPT" cmd1
  echo
  if [[ "$cmd1" != "nmcli dev show eth0 | grep -i dns" ]]; then
    print_error "Incorrect. Use: nmcli dev show eth0 | grep -i dns"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo "  IP4.DNS[1]:                             192.168.50.1"
  echo

  echo "  Step 2: Configure eth0 to use DNS server 8.8.8.8 (IPv4)."
  read -p "$PROMPT" cmd2
  echo
  if [[ "$cmd2" != "sudo nmcli con mod eth0 ipv4.dns 8.8.8.8" ]]; then
    print_error "Incorrect. Use: sudo nmcli con mod eth0 ipv4.dns 8.8.8.8"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo

  echo "  Step 3: Bring the eth0 connection up to apply the new DNS setting."
  read -p "$PROMPT" cmd3
  echo
  if [[ "$cmd3" != "sudo nmcli con up eth0" ]]; then
    print_error "Incorrect. Use: sudo nmcli con up eth0"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo "  Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/4)"
  echo

  echo "  Step 4: Verify eth0 now reports DNS server 8.8.8.8."
  read -p "$PROMPT" cmd4
  echo
  if [[ "$cmd4" != "nmcli dev show eth0 | grep -i dns" ]]; then
    print_error "Incorrect. Use: nmcli dev show eth0 | grep -i dns"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo "  IP4.DNS[1]:                             8.8.8.8"
  echo

  echo "  Step 5: Confirm /etc/resolv.conf is being managed by NetworkManager."
  read -p "$PROMPT" cmd5
  echo
  if [[ "$cmd5" != "cat /etc/resolv.conf" ]]; then
    print_error "Incorrect. Use: cat /etc/resolv.conf"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo "  # Generated by NetworkManager"
  echo "  search localdomain"
  echo "  nameserver 8.8.8.8"
  echo

  echo "  Step 6: Test DNS resolution for a public hostname (google.com)."
  read -p "$PROMPT" cmd6
  echo
  if [[ "$cmd6" != "ping -c 2 google.com" ]]; then
    print_error "Incorrect. Use: ping -c 2 google.com"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo "  PING google.com (142.250.72.14) 56(84) bytes of data."
  echo "  64 bytes from 142.250.72.14: icmp_seq=1 ttl=116 time=18.3 ms"
  echo "  64 bytes from 142.250.72.14: icmp_seq=2 ttl=116 time=17.9 ms"
  echo
  echo "  --- google.com ping statistics ---"
  echo "  2 packets transmitted, 2 received, 0% packet loss, time 1002ms"
  echo

  echo "  Step 7: Open /etc/hosts using vim."
  read -p "$PROMPT" cmd7
  echo
  if [[ "$cmd7" != "sudo vim /etc/hosts" && "$cmd7" != "sudo vi /etc/hosts" ]]; then
    print_error "Incorrect. Use: sudo vim /etc/hosts"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo "  (vim opened)"
  echo

  echo "  Step 8: Add a local hostname mapping at the end of /etc/hosts."
  echo "          Type the EXACT line you added:"
  read -p "  > " hosts1
  if [[ "$hosts1" != "192.168.50.100 webserver" ]]; then
    print_error "Incorrect /etc/hosts entry."
    read -p "Press Enter to retry..." _
    continue
  fi
  echo
  echo "  (save and exit the editor)"
  echo

  echo "  Step 9: Verify the host entry resolves locally (without DNS) using getent."
  read -p "$PROMPT" cmd9
  echo
  if [[ "$cmd9" != "getent hosts webserver" ]]; then
    print_error "Incorrect. Use: getent hosts webserver"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo "  192.168.50.100   webserver"
  echo

  echo "  Step 10: Verify name service switch configuration includes hosts and dns."
  read -p "$PROMPT" cmd10
  echo
  if [[ "$cmd10" != "grep '^hosts:' /etc/nsswitch.conf" ]]; then
    print_error "Incorrect. Use: grep '^hosts:' /etc/nsswitch.conf"
    read -p "Press Enter to retry..." _
    continue
  fi
  echo "  hosts:      files dns myhostname"
  echo

  print_success "Excellent work."
  print_info "You successfully:"
  print_info "- inspected resolver configuration via nmcli and /etc/resolv.conf"
  print_info "- configured persistent DNS using NetworkManager (nmcli)"
  print_info "- validated public DNS resolution with ping"
  print_info "- added a local override using /etc/hosts"
  print_info "- verified local resolution with getent and checked nsswitch order"
  print_info "You earned $LAB_XP XP."

  award_xp $LAB_XP
  record_lab_completion

  completion_count=$(get_lab_completion_count)
  echo
  print_info "You've completed this lab $completion_count time(s)."
  echo
  center_text "Would you like to:"
  center_text "1) Retry this lab"
  center_text "2) Return to Sysadmin Lab Menu"
  echo
  read -p "  > " choice
  [[ "$choice" == "2" ]] && exit 0
done
